source /opt/homebrew/opt/antidote/share/antidote/antidote.zsh
autoload -U compinit && compinit
antidote load

eval "$(/opt/homebrew/bin/brew shellenv)"

eval "$(starship init zsh)"

source ~/.dotfiles/shell/aliases.zsh

source $(brew --prefix nvm)/nvm.sh
export NVM_DIR="$HOME/.nvm"
[ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"

